version: '3'

services:
  app:
      image: delivery-app
      build:
            context: .
            dockerfile: ./Dockerfile
      depends_on:
        - demo-mysql
      ports:
        - 8080:8080
      environment:
        - DATABASE_HOST=demo-mysql
        - DATABASE_USER=root
        - DATABASE_PASSWORD=root
        - DATABASE_NAME=db_delivery
        - DATABASE_PORT=3306
  demo-mysql:
    image: mysql:5.6
    ports:
          - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db_delivery
      - MYSQL_PASSWORD=root
      - MYSQL_USER=root